apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-microservices-application
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - scmProvider:
          cloneProtocol: https
          github:
            organization: deployment-demo
            tokenRef:
              secretName: github-token
              key: token
          filters:
            - labelMatch: helm
      - git:
          repoURL: https://github.com/deployment-demo/deployment-demo.git
          revision: HEAD
          files:
            - path: "versions/qa2.yaml"
  template:
    metadata:
      name: '{{ .repository }}'
    spec:
      project: "default"
      sources:
        - repoURL: '{{ .url }}'
          targetRevision: HEAD
          path: "helm/"
          helm:
           valueFiles:
             - $values/environments/qa2.yaml
           values: |
             image:
               tag: '{{ index .services .repository  }}'
        - repoURL: https://github.com/deployment-demo/deployment-demo.git
          targetRevision: HEAD
          ref: values
      destination:
          server: https://kubernetes.default.svc
          namespace: argo-demo
 
